### ISSUE TITLE
How do you automate your local debug.

### ISSUE THREAD

**Issue by elaijuh** [lzl124631x/LeetCode#2]
From your repo files, I assume you are not using vscode extensions for leetcode local debug as you write a bunch of scripts helping to automate the process. But  I cannot find the html file running those js scripts which I find very useful for scraping leetcode api data. Can you shed some light one your workflow? Thanks.

**Comment by elaijuh** [comment]
I think I figured it out:

1. Run `pick.js` in chrome console of an opening leetcode page to random pick a problem

2. Run `create.sh` to create a folder with `readme.md` and `s1.cpp` (from `*.bookmark.js` as template now for later use).

3. Run `readme.md` (js) in chrome console to get the html file and replace the `readme.md` with it.

4. Solving the problem.

5. Run `s1.cpp` (js) in chrome console to get the submission and replace the `s1.cpp` with it.

6. Run `checkin.sh` to git your update in.

It's a good use case to make a chrome extension though :D

**Comment by lzl124631x** [comment]
I mostly debug directly in LeetCode.com directly. In rare cases I debug using local IDE.
