### ISSUE TITLE
quiz.bookmark.js

### ISSUE THREAD

**Issue by elaijuh** [lzl124631x/LeetCode#3]
Since you already have a script to extract solution `answer.bookmark.js`, I think it will be convenient to just extract the solution and paste it in this script.

**Comment by lzl124631x** [comment]
I see your point. But sometimes I only want to update the problem description to keep it up-to-date and don't want to copy the solution. For me it's a good balance for now.

BTW, I'm using my Chrome extension [LeetCoder](https://chrome.google.com/webstore/detail/leetcoder/gkmoalkjclphfhgnhdlilebaolpdkgpf) instead now.
