### ISSUE TITLE
Time/Space complexity clarifications

### ISSUE THREAD

**Issue by hieucnguyen** [lzl124631x/LeetCode#5]
First of all, thanks so much for this repo as a very helpful reference. I have a question regarding one of time/space complexity of the code: https://github.com/lzl124631x/LeetCode/tree/master/leetcode/505.%20The%20Maze%20II

Are you sure the Time is O(mn)? Looks like from the discussion and solution tab the best they can achieve with BFS/DFS is O(m*n*max(m,n)). Even with PriorityQueue the best achieved is O(m*n*log(m*n)). Reference:
https://leetcode.com/problems/the-maze-ii/solution/
https://leetcode.com/problems/the-maze-ii/discuss/?currentPage=1&orderBy=most_votes&query=

**Comment by lzl124631x** [comment]
@hieucnguyen I updated my note. Please let me know if you have further questions. My estimation of the PQ solution is different from the official solution. I see some challenge to that official time complexity in the comments as well. I feel it's a bit hard to have an accurate estimate.
